public enum GameStateEnum
{
    //Game state name  // Value
    PROPOSAL_INITIALIZATION,  //0
    PROPOSAL_ONGOING,  //1
    PROPOSAL_FULL_DECISION,  //2
    ANIMATION_PROPOSAL_INITIALIZATION,  //3
    ANIMATION_PROPOSAL_FINALIZATION,  //4
    ANIMATION_NEWMONTH_INITIALIZATION, //5
    EVENT_CHECK, //6
    ANIMATION_NEWMONTH_FINALIZATION //7
}