public enum GameStateEnum
{
    //Game state name  // Value
    PROPOSAL_LOADING,  //0
    PROPOSAL_TEMP_DECISION,  //1
    PROPOSAL_FULL_DECISION,  //2
    PROPOSAL_STATS_UPDATED,  //3
    ANIMATION_PROPOSAL_LOADING,  //4
    ANIMATION_PROPOSAL_UNLOADING  //5
}